---
title: "Predicting Pancreatic Cancer Using Urinary Biomarkers"
author: "Helen Yang/Yao Xin"
date: "05/09/2021"
output: pdf_document
---

```{r packages and data preparation}
rm(list=ls())
library(ggplot2)
library(readr)
library(pROC)
library(MASS)

#read in data from your computer
deb2020 <- read_csv("Your own path/Debernardi et al 2020 data.csv")
```

```{r recoding}

#2-category diagnosis
deb2020$DIAG <- as.factor(ifelse(deb2020$diagnosis=="3",1,0))
deb2020$DIAG <- ordered(deb2020$DIAG , levels = c(0,1), 
                            labels = c("Control/Benign", "PDAC"))

#diagnosis
deb2020$diagnosis <- ordered(deb2020$diagnosis , levels = c(1,2,3), labels = c("Control", "Benign", "Malignant"))


#sex
deb2020$sex1<-NA
deb2020$sex1[deb2020$sex=="F"]<-2
deb2020$sex1[deb2020$sex=="M"]<-1
deb2020$sex1 <- ordered(deb2020$sex1 , levels = c(1,2), labels = c("Male", "Female"))
```


```{r descriptive statistics}
summary(deb2020$age)

p<-ggplot(deb2020, aes(x=as.numeric(age),fill=sex))+
  geom_histogram(stat="count", width=0.9, fill="steelblue")+
  theme_minimal()+
  labs(title="Age Distribution in the Debernardi2020 sample")
p+scale_x_continuous(name="Age", breaks=c(20,40,60,80,100))

table1<-table(deb2020$sex1)
table1
prop.table(table1)

ggplot(deb2020, aes(x=factor(sex1),fill=sex))+
  geom_bar(stat="count", width=0.3, fill="steelblue")+
  theme_minimal()+
  labs(x = "Gender", title="Gender Frequencies in the Debernardi2020 sample")

table1<-table(deb2020$DIAG)
table1
prop.table(table1)

ggplot(deb2020, aes(x=factor(DIAG),fill=DIAG))+
  geom_bar(stat="count", width=0.3, fill="steelblue")+
  theme_minimal()+
  labs(x = "Diagnosis", title="PDAC diagnosis in the Debernardi2020 sample")

table3<-table(deb2020$stage)
table3
prop.table(table3)
ggplot(data=subset(deb2020,!is.na(stage)), aes(x=factor(stage),fill=DIAG))+
  geom_bar(stat="count", width=0.3, fill="steelblue")+
  theme_minimal()+
  labs(x = "Stage", title="PDAC stages among 199 malignant patients in the Debernardi2020 sample")
```

```{r randomly choose 80% as training set and 20% as testing set}
set.seed(1)

index = sample(1:590)
train_ind = index[1:(590*80/100)]
test_ind = index[(590*80/100+1):590]
train = deb2020[train_ind,]
test = deb2020[test_ind,] 
```


```{r bivariate visualization}
ggplot(data = deb2020, aes(x = age , y = creatinine , color = diagnosis)) + geom_point(size=1) + scale_color_brewer(palette = "Set1", direction = -1)

ggplot(data = deb2020, aes(x = age , y = LYVE1 , color = diagnosis)) + geom_point(size=1) + scale_color_brewer(palette = "Set1", direction = -1)

ggplot(data = deb2020, aes(x = age , y = REG1B , color = diagnosis)) + geom_point(size=1) + scale_color_brewer(palette = "Set1", direction = -1)

ggplot(data = deb2020, aes(x = age , y = TFF1 , color = diagnosis)) + geom_point(size=1) + scale_color_brewer(palette = "Set1", direction = -1)
```


```{r  logistic regression}
# logistic regression
log.fit <- glm(DIAG~creatinine+LYVE1+REG1B+TFF1+age+sex, data=train,family = 'binomial')
summary(log.fit)
exp(log.fit$coefficients)

log.pred <- predict(log.fit, newdata = test, type = 'response')
log.pred.class = ifelse(log.pred > 0.5, 1, 0)

table <- table(test$DIAG, log.pred.class)
table

roc(test$DIAG,log.pred,plot = TRUE, print.auc = TRUE)
title(main = "ROC curve for distinguishing PDAC from control/benign with logistic regression")

sum(diag(prop.table(table)))
```

```{r LDA}
lda.fit <- lda(DIAG~creatinine+LYVE1+REG1B+TFF1+sex+age, data = train)
lda.fit

lda_pred <- predict(lda.fit, newdata = test, type = 'response')
newgroup <- lda_pred$class
tab <- table(test$DIAG,newgroup)
plot(tab)
accuracy <- sum(diag(prop.table(tab)))
accuracy


roc(test$DIAG,lda_pred$posterior[,2],plot=TRUE, legacy.axes = TRUE, print.auc = TRUE, percent =TRUE, xlab="Sensitivity", ylab="Specificity", main = "ROC curve for distinguishing PDAC from control/benign with LDA")

```

```{r QDA}
qda.fit <- qda(DIAG~creatinine+LYVE1+REG1B+TFF1+sex+age, data = train)
qda.fit

qda_pred <- predict(qda.fit, newdata = test, type = 'response')
newgroup2 <- qda_pred$class
tab2 <- table(test$DIAG,newgroup2)
plot(tab2)
accuracy2 <- sum(diag(prop.table(tab2)))
accuracy2

roc(test$DIAG,qda_pred$posterior[,2],plot=TRUE, legacy.axes = TRUE, print.auc = TRUE, 
percent =TRUE, xlab="Sensitivity", ylab="Specificity", main = "ROC curve for distinguishing PDAC from control/benign with QDA")

```

```{r model selection}
deb2020$DIAG <- as.numeric(deb2020$DIAG)
cor.test(deb2020$DIAG, deb2020$creatinine, method="pearson")
cor.test(deb2020$DIAG, deb2020$LYVE1, method="pearson")
cor.test(deb2020$DIAG, deb2020$REG1A, method="pearson")
cor.test(deb2020$DIAG, deb2020$TFF1, method="pearson")
```

